language: cpp

os: osx
osx_image: xcode9.2

branches:
  only:
    - master

install:
  # clone 3rd-party repos
  - git clone -q https://github.com/Skycoder42/QHotkey.git ../3rdparty/QHotkey
  # download resources & prebuilt libraries
  - |
    curl "https://www.dropbox.com/s/15s4v2eos5p6fcv/Qt-5.9.3-m13-clang9.tar.xz?dl=1" -L -s | tar xJ
    qtdir=$(ls | grep Qt)
    ./scripts/patch_qt.py -q $qtdir -d /usr/local/$qtdir
    sudo mv $qtdir /usr/local/
    export PATH="/usr/local/$qtdir/bin:$PATH"

before_script:
  - lupdate -no-obsolete DigitalClock.pro
  - qmake -config release -r DigitalClock.pro

script: make -j2
