language: cpp

os: osx
osx_image: xcode9.3

branches:
  only:
    - master

install:
  # clone 3rd-party repos
  - git clone -q -b master --depth 1 https://github.com/Skycoder42/QHotkey.git ../3rdparty/QHotkey
  - git clone -q -b master --depth 1 https://github.com/itay-grudev/SingleApplication.git ../3rdparty/SingleApplication
  # download resources & prebuilt libraries
  - |
    curl "https://www.dropbox.com/s/hy21ly9sb3jn1vv/Qt-5.9.6-m13-xcode9.4.tar.xz?dl=1" -L -s | tar xJ
    qtdir=$(ls | grep Qt)
    ./scripts/patch_qt.py -q $qtdir -d /usr/local/$qtdir
    sudo mv $qtdir /usr/local/
    export PATH="/usr/local/$qtdir/bin:$PATH"

before_script:
  - lupdate -no-obsolete DigitalClock.pro
  - qmake -config release -r DigitalClock.pro

script: make -j2
